[
	uuid(58b19028-b9a0-4c25-887f-aca58b584d1b),
	version(1.0),
]
interface DefaultIfName
{

	long Proc0(
		[in]/* simple_ref */[size_is(arg_2)]/*[range(0,0)]*/ byte* arg_1,
		[in]long arg_2,
		[out]/* simple_ref */ /* [DBG] FC_CVARRAY */[size_is(arg_4)]/*[range(0,16777216)]*/[length_is( *arg_5)]byte* arg_3/*[] CONFORMANT_ARRAY*/,
		[in][range(0, 16777216)] long arg_4,
		[out]/* simple_ref */long* arg_5);
}
